---
- hosts: "{{ hosts1_override | default('proxmox_compute') }}"
  collections:
    - kharyam.lab_setup
  roles:
    - role: shutdown
  ignore_unreachable: true

#- hosts: "{{ hosts2_override | default('nas') }}"
#  collections:
#    - kharyam.lab_setup
#  roles:
#    - role: shutdown
#  ignore_unreachable: true
#
